### ISSUE TITLE
UnsatisfiedLinkError on Linux

### ISSUE THREAD

**Issue by gatesn** [TileDB-Inc/TileDB-Trino#76]
I seem to get this link error after adding the jar to plugin/tiledb and creating a catalog/tiledb.properties file.

```
1) [Guice/ErrorInjectingConstructor]: UnsatisfiedLinkError: 'long io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp()'
  at TileDBClient.<init>(TileDBClient.java:73)
  at TileDBModule.configure(TileDBModule.java:72)
  while locating TileDBClient

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: UnsatisfiedLinkError: 'long io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp()'
        at io.tiledb.libtiledb.tiledbJNI.new_tiledb_config_tpp(Native Method)
        at io.tiledb.libtiledb.tiledb.new_tiledb_config_tpp(tiledb.java:541)
        at Config.<init>(Config.java:68)
        at TileDBClient.buildConfig(TileDBClient.java:272)
        at TileDBClient.<init>(TileDBClient.java:78)
        at TileDBClient$$FastClassByGuice$$2472331.GUICE$TRAMPOLINE(<generated>)
        at TileDBClient$$FastClassByGuice$$2472331.apply(<generated>)
        at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at ConstructorInjector.provision(ConstructorInjector.java:114)
        at ConstructorInjector.access$000(ConstructorInjector.java:33)
        at ConstructorInjector$1.call(ConstructorInjector.java:98)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at LifeCycleModule.provision(LifeCycleModule.java:54)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at ConstructorInjector.construct(ConstructorInjector.java:93)
        at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at SingletonScope$1.get(SingletonScope.java:169)
        at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at Guice.createInjector(Guice.java:87)
        at Bootstrap.initialize(Bootstrap.java:270)
        at TileDBConnectorFactory.create(TileDBConnectorFactory.java:68)
        at ConnectorManager.createConnector(ConnectorManager.java:366)
        at ConnectorManager.createCatalog(ConnectorManager.java:218)
        at ConnectorManager.createCatalog(ConnectorManager.java:210)
        at ConnectorManager.createCatalog(ConnectorManager.java:196)
        at StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
        at StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at Server.doStart(Server.java:125)
        at Server.lambda$start$0(Server.java:78)
        at io.trino.$gen.Trino_363____20211007_125716_1.run(Unknown Source)
        at Server.start(Server.java:78)
        at TrinoServer.main(TrinoServer.java:38)
```

**Comment by Shelnutt2** [comment]
@gatesn are you using the prebuilt jars from the 1.8.0 release or did you build it from source yourself? If you build it from source can you please run:
```
jar -tf /tmp/trino-tiledb-357.jar  | grep lib/
```

It should produce output such as:
```lib/
lib/libtiledb.dylib
lib/libtiledb.so
lib/libtiledbjni.so
lib/libtiledbjni.dylib
lib/tiledb.dll
lib/tiledbjni.dll
```

Mainly looking to see if the `lib/libtiledb.so`, and `lib/libtiledbjni.so` files show up for linux.
